import fs from 'fs/promises';
import path from 'path';
import sharp from 'sharp';
import { toPosixPath, writeFileAtomic } from './fs-utils.ts';

const FAR_THEME_COLOR = '#0b3954';
const FAR_PWA_ID = './far-pwa';
const FAR_ICON_SVG = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <rect width="512" height="512" fill="${FAR_THEME_COLOR}"/>
  <path d="M0 382 256 338l256 44v130H0z" fill="#082c46"/>
  <circle cx="256" cy="117" r="57" fill="none" stroke="#f6bd3b" stroke-width="10"/>
  <path d="m256 47 13 57 46 13-46 13-13 57-13-57-46-13 46-13z" fill="#f6bd3b"/>
  <path d="M256 78v78M217 117h78" stroke="#fff7e6" stroke-width="5" stroke-linecap="round"/>
  <text x="256" y="321" fill="#fffdf6" font-family="Inter,Segoe UI,Arial,sans-serif" font-size="150" font-weight="800" letter-spacing="-5" text-anchor="middle">FAR</text>
  <path d="M36 431h157l63-34 63 34h157" fill="none" stroke="#5f91d8" stroke-width="15" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M256 397v87" stroke="#f6bd3b" stroke-width="8" stroke-dasharray="13 12"/>
</svg>`;

const PWA_MARKER = '<!-- FAR PWA support -->';

function localReference(fileName) {
    const normalized = toPosixPath(fileName);
    return normalized.startsWith('.') ? normalized : `./${normalized}`;
}

function buildServiceWorker({ cacheName, offlineShell, precache }) {
    return `/* Generated by build-far.ts. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const OFFLINE_SHELL = ${JSON.stringify(offlineShell)};
const PRECACHE_URLS = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => cache.addAll(PRECACHE_URLS))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((keys) => Promise.all(keys
                .filter((key) => key.startsWith('far-shell-') && key !== CACHE_NAME)
                .map((key) => caches.delete(key))))
            .then(() => self.clients.claim())
    );
});

self.addEventListener('fetch', (event) => {
    const request = event.request;
    const url = new URL(request.url);
    if (request.method !== 'GET' || url.origin !== self.location.origin) return;

    const networkFirst = request.mode === 'navigate' || request.destination === 'document';
    const network = () => fetch(request).then((response) => {
        if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
        }
        return response;
    });

    event.respondWith(
        networkFirst
            ? network().catch(() => caches.match(request, { ignoreSearch: true })
                .then((cached) => cached || caches.match(OFFLINE_SHELL)))
            : caches.match(request, { ignoreSearch: true }).then((cached) => cached || network())
    );
});
`;
}

export function buildFarManifest(shellRef) {
    return {
        name: 'Federal Aviation Regulations',
        short_name: 'FAR',
        description: 'Browsable Federal Aviation Regulations from Title 14 CFR.',
        id: FAR_PWA_ID,
        start_url: shellRef,
        scope: './',
        display: 'standalone',
        display_override: ['standalone', 'browser'],
        background_color: '#ffffff',
        theme_color: FAR_THEME_COLOR,
        lang: 'en-US',
        icons: [
            { src: 'icons/far-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
            { src: 'icons/far-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' }
        ]
    };
}

export function addPwaMetadata(html, {
    manifestRef = './manifest.webmanifest',
    iconRef = './icons/apple-touch-icon.png',
    workerRef = './service-worker.js'
} = {}) {
    const source = String(html || '');
    if (source.includes(PWA_MARKER)) return source;
    if (!/<\/head>/i.test(source) || !/<\/body>/i.test(source)) {
        throw new Error('Cannot add FAR PWA metadata: generated shell is missing </head> or </body>.');
    }

    function insertBeforeClosingTag(value, closingTag, content, fromEnd = false) {
        const lower = value.toLowerCase();
        const index = fromEnd ? lower.lastIndexOf(closingTag) : lower.indexOf(closingTag);
        if (index < 0) return value;
        return `${value.slice(0, index)}${content}${value.slice(index)}`;
    }

    const head = `${PWA_MARKER}
  <link rel="manifest" href="${manifestRef}">
  <link rel="apple-touch-icon" href="${iconRef}">
  <meta name="theme-color" content="${FAR_THEME_COLOR}">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="apple-mobile-web-app-title" content="FAR">
`;
    const worker = `${PWA_MARKER}
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('${workerRef}');
      });
    }
  </script>
`;

    return insertBeforeClosingTag(
        insertBeforeClosingTag(source, '</head>', head),
        '</body>',
        worker,
        true
    );
}

export async function writeFarPwaFiles({
    htmlDir,
    shellFileName,
    partFiles = [],
    buildVersion = String(Date.now())
}) {
    const baseDir = path.resolve(htmlDir);
    const iconDir = path.join(baseDir, 'icons');
    await fs.mkdir(iconDir, { recursive: true });
    await writeFileAtomic(path.join(iconDir, 'far-icon.svg'), FAR_ICON_SVG);

    const icon = sharp(Buffer.from(FAR_ICON_SVG));
    const [icon192, icon512, appleTouchIcon] = await Promise.all([
        icon.clone().resize(192, 192).png().toBuffer(),
        icon.clone().resize(512, 512).png().toBuffer(),
        icon.clone().resize(180, 180).png().toBuffer()
    ]);
    await Promise.all([
        writeFileAtomic(path.join(iconDir, 'far-192.png'), icon192),
        writeFileAtomic(path.join(iconDir, 'far-512.png'), icon512),
        writeFileAtomic(path.join(iconDir, 'apple-touch-icon.png'), appleTouchIcon)
    ]);

    const shellRef = localReference(shellFileName);
    const pwaFiles = [
        'manifest.webmanifest',
        'service-worker.js',
        'icons/far-icon.svg',
        'icons/far-192.png',
        'icons/far-512.png',
        'icons/apple-touch-icon.png'
    ];
    const manifest = buildFarManifest(shellRef);
    await writeFileAtomic(path.join(baseDir, 'manifest.webmanifest'), `${JSON.stringify(manifest, null, 2)}\n`);

    const cacheFiles = new Set([
        shellRef,
        './manifest.webmanifest',
        './icons/far-icon.svg',
        './icons/far-192.png',
        './icons/far-512.png',
        './icons/apple-touch-icon.png'
    ]);
    for (const file of partFiles) {
        const stat = await fs.stat(file);
        if (!stat.isFile()) {
            throw new Error(`Cannot precache FAR asset because it is not a file: ${file}`);
        }
        cacheFiles.add(localReference(toPosixPath(path.relative(baseDir, file))));
    }
    cacheFiles.add('./service-worker.js');

    await writeFileAtomic(
        path.join(baseDir, 'service-worker.js'),
        buildServiceWorker({
            cacheName: `far-shell-${String(buildVersion).replace(/\D/g, '')}`,
            offlineShell: shellRef,
            precache: [...cacheFiles]
        })
    );

    return {
        manifestRef: './manifest.webmanifest',
        iconRef: './icons/apple-touch-icon.png',
        workerRef: './service-worker.js',
        pwaFiles
    };
}
